# Generated by Django 4.2.7 on 2023-11-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_card_contact_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='https://drive.google.com/file/d/1Aop40E-z76CiifTSXkAICoQgfZQ36EQL/view?usp=sharing', null=True, upload_to='images/'),
        ),
    ]
