# Generated by Django 4.2.7 on 2023-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='https://drive.google.com/file/d/1Aop40E-z76CiifTSXkAICoQgfZQ36EQL/view?usp=sharing', null=True, upload_to='images/'),
        ),
    ]
