# Generated by Django 4.2.7 on 2023-11-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descripition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descripition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
