# Generated by Django 4.2.7 on 2023-11-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_descripition_aboutcard_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='introcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
    ]
