# Generated by Django 4.2.7 on 2023-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_aboutcard_image_remove_introcard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcard',
            name='sub_title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='sub_title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='sub_title3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introcard',
            name='sub_title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introcard',
            name='sub_title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introcard',
            name='sub_title3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
