# Generated by Django 4.2.7 on 2023-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_aboutcard_sub_title1_aboutcard_sub_title2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introcard',
            name='sub_title3',
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcard',
            name='sub_title4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='introcard',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
