# Generated by Django 4.2.7 on 2023-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_introcard_sub_title3_aboutcard_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
