# Generated by Django 4.2.7 on 2023-11-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_contact_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCard',
        ),
        migrations.DeleteModel(
            name='IntroCard',
        ),
    ]
